version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    env_file:
      - .env
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - my_network
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - db
volumes:
  mysql-data:
  init:
networks:
  my_network:
    driver: bridge